package tokenauth

import (
	"encoding/base64"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"github.com/taiypeo/spotifygo"
	"github.com/taiypeo/spotifygo/apierrors"
	"github.com/taiypeo/spotifygo/requests"
)

// RefreshableAuthToken is a struct that represents a token that
// can refresh after expiring. It is generated by
// authorization code flow.
type RefreshableAuthToken struct {
	RefreshToken string
	ScopedAuthToken
}

// NewRefreshableAuthToken creates a new RefreshableAuthToken.
// authCode is the authorization code returned from the request to the /authorize endpoint;
// redirectURI is the same redirect_uri that was supplied when requesting the authorization code;
// clientId is the Spotify application client id;
// clientSecret is the Spotify application client secret.
func NewRefreshableAuthToken(
	authCode,
	redirectURI,
	clientID,
	clientSecret string,
) (RefreshableAuthToken, apierrors.TypedError) {
	payload := fmt.Sprintf(
		"grant_type=authorization_code&code=%s&redirect_uri=%s",
		authCode,
		redirectURI,
	)
	encodedAuthorizationHeader := "Basic " + base64.StdEncoding.EncodeToString(
		[]byte(fmt.Sprintf("%s:%s", clientID, clientSecret)),
	)

	response, err := requests.PostAuthorization(
		map[string]string{"Authorization": encodedAuthorizationHeader},
		payload,
	)
	if err != nil {
		return RefreshableAuthToken{}, err
	}

	var decodedResponse struct {
		AccessToken  string `json:"access_token"`
		TokenType    string `json:"token_type"`
		Scope        string `json:"scope"`
		ExpiresIn    int64  `json:"expires_in"`
		RefreshToken string `json:"refresh_token"`
	}
	if err := json.Unmarshal([]byte(response.JSONBody), &decodedResponse); err != nil {
		return RefreshableAuthToken{}, apierrors.NewBasicErrorFromError(err)
	}

	if decodedResponse.TokenType != "Bearer" {
		return RefreshableAuthToken{},
			apierrors.NewBasicErrorFromString("token_type is not Bearer")
	}

	var createdRefreshableAuthToken RefreshableAuthToken
	createdRefreshableAuthToken.CreationTime = time.Now()
	createdRefreshableAuthToken.AccessToken = decodedResponse.AccessToken
	createdRefreshableAuthToken.ExpiresIn = decodedResponse.ExpiresIn
	createdRefreshableAuthToken.RefreshToken = decodedResponse.RefreshToken
	createdRefreshableAuthToken.Scope = strings.Split(decodedResponse.Scope, " ")
	return createdRefreshableAuthToken, nil
}

// Refresh refreshes the access token using the refresh token.
// clientId is the Spotify application client id;
// clientSecret is the Spotify application client secret.
func (auth *RefreshableAuthToken) Refresh(
	clientID,
	clientSecret string,
) (spotifygo.APIResponse, apierrors.TypedError) {
	payload := fmt.Sprintf("grant_type=refresh_token&refresh_token=%s", auth.RefreshToken)
	encodedAuthorizationHeader := "Basic " + base64.StdEncoding.EncodeToString(
		[]byte(fmt.Sprintf("%s:%s", clientID, clientSecret)),
	)

	response, err := requests.PostAuthorization(
		map[string]string{"Authorization": encodedAuthorizationHeader},
		payload,
	)
	if err != nil {
		return response, err
	}

	var decodedResponse struct {
		AccessToken string `json:"access_token"`
		TokenType   string `json:"token_type"`
		Scope       string `json:"scope"`
		ExpiresIn   int64  `json:"expires_in"`
	}
	if err := json.Unmarshal([]byte(response.JSONBody), &decodedResponse); err != nil {
		return response, apierrors.NewBasicErrorFromError(err)
	}

	if decodedResponse.TokenType != "Bearer" {
		return response, apierrors.NewBasicErrorFromString("token_type is not Bearer")
	}

	auth.CreationTime = time.Now()
	auth.AccessToken = decodedResponse.AccessToken
	auth.ExpiresIn = decodedResponse.ExpiresIn
	auth.Scope = strings.Split(decodedResponse.Scope, " ")

	return response, nil
}
