package tokenauth

// PKCERefreshableAuthToken is a struct that represents a token that
// can refresh after expiring. It can be generated by
// authorization code flow with proof key for code exchange (PKCE).
// While identical to RefreshableAuthToken, a new struct is necessary
// because the refreshing behavior is different.
type PKCERefreshableAuthToken struct {
	RefreshToken string
	ScopedAuthToken
}
