package tokenauth

import "time"

// AuthToken is a struct that represents a simple token
// generated by client credentials flow.
type AuthToken struct {
	AccessToken  string
	ExpiresIn    int64
	CreationTime time.Time
}

// ScopedAuthToken is a struct that represents a token with
// scope that was generated by implicit grant flow.
type ScopedAuthToken struct {
	Scope []string
	AuthToken
}

// RefreshableAuthToken is a struct that represents a token that
// can refresh after expiring. It can be generated by
// authorization code flow.
type RefreshableAuthToken struct {
	RefreshToken string
	ScopedAuthToken
}

// PKCERefreshableAuthToken is a struct that represents a token that
// can refresh after expiring. It can be generated by
// authorization code flow with proof key for code exchange (PKCE).
// While identical to RefreshableAuthToken, a new struct is necessary
// because the refreshing behavior is different.
type PKCERefreshableAuthToken struct {
	RefreshToken string
	ScopedAuthToken
}

// GetToken returns a token that is used in Spotify REST API to authorize
// user actions.
func (auth *AuthToken) GetToken() string {
	return "Bearer " + auth.AccessToken
}
